
# MySQL数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dataex?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: abc123
mybatis:
  #配置MyBatis的xml配置文件路径
  mapper-locations: classpath:mapper/*.xml
  #配置XML映射文件中指定的实体类别名路径
  type-aliases-package: com.example.javatest
#配置日志  打印sql语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8889


local:
  img:
    path: F://
